### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by zzgames** [H4wk507/QtCalculator#4]
Running ```cmake ..```  I'm getting this error: 
```CMake Error at CMakeLists.txt:57 (add_executable): Cannot find source file: ui_calculator.h``` 

https://github.com/H4wk507/QtCalculator/blob/4c0870ced9a453f4b52668fd5086b6d4c8560114/CMakeLists.txt#L23

**Comment by H4wk507** [comment]
@ZZaccount1 I forgot to add this file to git, but apparently, ui_calculator.h is not needed for compilation, because QT automatically creates this file, so I removed it from cmake altogether. Hope it works for you now, and thanks for raising an issue!
